### ISSUE TITLE
English -> French translations

### ISSUE THREAD

**Issue by RonRahaman** [gt-ospo/poirot-summer-2024#3]
## Description

Some French speakers have noted that characters' casual usage of English is a barrier to French readers.  They have requested a few English to French translations.

See also #2 

## Tasks

- [ ] In `01-western-star.txt` change occurence of "My God" to "_Mon Dieu_"
- [ ] Do the same in `02-marsdon-manor.txt`
- [ ] Do the same in `03-cheap-flat.txt`
- [ ] Do the same in `04-hunters-lodge.txt`
